- appName: 京东阅读
  packageName: com.jd.app.reader
  skipIds:
    - id: com.jd.app.reader:id/mJumpBtn
      fileUrl: 7ba85f98-5b07-4947-95e0-dca6431b1fc6&nodeId=10
  skipBounds:
    - bound: 1243,176,1383,316
      resolution: 1440x3200
      fileUrl: 20f3db03-af60-4dc3-885a-b954b985931f&nodeId=14


- appName: 前程无忧51Job
  packageName: com.job.android
  skipIds:
    - id: com.job.android:id/skipBtn
      fileUrl: ee283a25-cbbf-43b0-84dd-aaf9ccf24c83&nodeId=10

- appName: 酷安
  packageName: com.coolapk.market
  skipTexts:
    - text: 跳过
      length: 4
      fileUrl: 94969846-73e3-41de-aca0-ad9994566fc6&nodeId=46
  skipBounds:
    - bound: 1244,176,1384,316
      fileUrl: 92e729ea-dd19-4384-93af-ec7581f306cf&nodeId=66

- appName: 铁路12306
  packageName: com.MobileTicket
  skipIds:
    - id: com.MobileTicket:id/tv_skip
      fileUrl: b8592c72-1a8a-42ea-8022-2ba15bc83444&nodeId=9

- appName: 人人视频
  packageName: com.example.pptv
  skipTexts:
    - text: 跳过
      length: 7
      fileUrl: 84603cb6-3647-42aa-a0f9-e013a3c1e74c&nodeId=67

- appName: CSDN
  packageName: net.csdn.csdnplus
  skipTexts:
    - text: 跳过
      length: 5
      fileUrl: 7d45a0ad-f0ce-4856-b38b-dd545bfadeb5&nodeId=28
  skipBounds:
    - bound: 1244,176,1384,316
      fileUrl: e2c456c9-2db5-4ff9-9f79-f42acf557358&nodeId=13

- appName: 豆瓣
  packageName: com.douban.frodo
  skipTexts:
    - text: 跳过
      length: 3
      fileUrl: 7aa2544b-8a80-41f3-bf0c-ee03c7cf83b2&nodeId=107
  skipIds:
    - id: com.douban.frodo:id/ad_mark
      fileUrl: cfe9660a-1d45-4904-a8a7-8d846faa1a49&nodeId=14
      click: 1280,180

- appName: 什么值得买
  packageName: com.smzdm.client.android
  skipIds:
    - id: com.smzdm.client.android:id/tv_skip
      fileUrl: 2adae253-623d-4fd3-ad75-b5b32b667dcd&nodeId=18

- appName: 哔哩哔哩
  packageName: tv.danmaku.bili
  skipIds:
    - id: tv.danmaku.bili:id/count_down
      fileUrl: 368caf09-c152-4f6b-b8dd-3ee4718df65d&nodeId=26

- appName: 小时工记账
  packageName: com.julangling.xsgjz
  skipTexts:
    - text: 跳过
      length: 4
      fileUrl: 28b730a3-5ac7-44c7-8f8a-9daf1b8effbe&nodeId=27
  skipBounds:
    - bound: 1244,176,1384,316
      fileUrl: 43bcef4b-4b5b-4b63-a7f2-ad28e4f5f690&nodeId=30

- appName: 搜狗输入法
  packageName: com.sohu.inputmethod.sogou
  skipTexts:
    - text: 跳过
      length: 2
      fileUrl: 450b0add-b8e2-4cac-9b49-015744bb786f&nodeId=14

- appName: 菜鸟
  packageName: com.cainiao.wireless
  skipTexts:
    - text: 跳过
      length: 4
      fileUrl: 5656e116-5a93-44da-8687-1a1dec170984&nodeId=11

- appName: 高德地图
  packageName: com.autonavi.minimap
  skipTexts:
    - text: 跳过
      length: 2
      fileUrl: 57861a13-956b-4ae1-be60-d77c33b82010&nodeId=61

- appName: 帆书
  packageName: io.dushu.fandengreader
  skipIds:
    - id: io.dushu.fandengreader:id/layout_skip
      fileUrl: 88ad5f6b-e65b-4424-be8e-ab57e0eb613b&nodeId=9

- appName: 腾讯微云
  packageName: com.qq.qcloud
  skipBounds:
    - bound: 1223,177,1384,289
      activityName: com.qq.qcloud.activity.WeiyunRootActivity
      fileUrl: a310356a-4841-40fd-8a4f-314e77318230&nodeId=10

- appName: 鹿路通
  packageName: com.psbc.citizencard
  skipTexts:
    - text: 跳过
      length: 4
      fileUrl: bb3de897-19d4-4c6d-ac7a-e11130420b4a&nodeId=8

- appName: 滴滴出行
  packageName: com.sdu.didi.psnger
  skipTexts:
    - text: 跳过
      length: 2
      fileUrl: e835b293-7845-4988-9423-fe7f9d740d43&nodeId=13

- appName: 知乎
  packageName: com.zhihu.android
  skipIds:
    - id: com.zhihu.android:id/btn_skip
      fileUrl: 812b304e-63fd-42da-b200-7497a2e635c4&nodeId=21

- appName: 汽水音乐
  packageName: com.luna.music
  skipBounds:
    - bound: 1244,176,1384,316
      fileUrl: ab69a19e-56e8-4983-9656-cdbab1b09682&nodeId=13

- appName: 爱奇艺
  packageName: com.qiyi.video
  skipTexts:
    - text: 关闭

- appName: 爱奇艺极速版
  packageName: com.qiyi.video.lite
  skipTexts:
    - text: 关闭