name: Deploy SKIP static file

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Latest Version Number
      run: |
        echo "1.4" >> dist/latest_version.txt
    
    - name: SKIP Config
      run: |
        cp app/src/main/assets/skip_config.yaml dist/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist